### ISSUE TITLE
Dependencies confusion

### ISSUE THREAD

**Issue by kavi87** [spring-cloud-samples/aws-refapp#25]
Starting a new Spring boot 2.5 project with Spring Cloud AWS is very confusing. Should we use io.awspring.cloud or org.springframework.cloud ? The documentation is not very verbose on the dependencies to use. 
I have been completely unable to get properties like aws.paramstore.prefix to be recognized in a bootstrap file, they seem to be completely ignored. Why ?
If there are missing dependencies, what are they ? 
I'm unable to find the simplest pom.xml with a config that works. I've reverted to using an old Spring boot version and the org.springframework.cloud dependencies that are perfectly fine.
The documentation would highly benefit from a clear example of dependencies and why nothing seems to autoconfigure.

**Comment by spencergibb** [comment]
Spring cloud AWS is no longer part of the spring cloud release train. See the awspring documentation

**Comment by kavi87** [comment]
Ok, it's entirely my fault. I went from Spring Boot 2.3 to 2.5 without paying attention to the fact that there was a major change in the way profile specific files are now loaded.
